name: autofinder
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ^3.11.1

dependencies:
  adaptive_theme: ^3.7.2
  cloud_firestore: ^6.4.1
  firebase_core: ^4.9.0
  flutter:
    sdk: flutter
  flutter_map: ^7.0.2
  form_validator: ^2.1.1
  geocoding: ^4.0.0
  geolocator: ^14.0.2
  google_sign_in: ^7.2.0
  http: ^1.6.0
  image_picker: ^1.2.2
  latlong2: ^0.9.1
  lottie: ^3.3.1
  provider: ^6.1.5+1
  shared_preferences_android: ^2.4.23

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - images/
    - json/
