name: autofinder
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0+1

environment:
  # sdk: ^3.11.1
  sdk: ^3.12.0

dependencies:
  adaptive_theme: ^3.7.2
  cloud_firestore: ^6.4.1
  firebase_core: ^4.9.0
  firebase_storage: ^13.4.1
  flutter:
    sdk: flutter
  flutter_localization: ^0.4.0
  flutter_map: ^7.0.2
  form_validator: ^2.1.1
  geocoding: ^4.0.0
  geoflutterfire_plus: ^0.0.34
  geolocator: ^14.0.2
  google_sign_in: ^7.2.0
  http: ^1.6.0
  image_picker: ^1.2.2
  latlong2: ^0.9.1
  lottie: ^3.3.1
  provider: ^6.1.5+1
  share_plus: ^12.0.2
  shared_preferences: ^2.3.5
  shared_preferences_android: ^2.4.23
  translator: ^1.0.4+1
  url_launcher: ^6.3.2
  webview_flutter: ^4.13.1
  webview_flutter_web: ^0.2.3+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - images/
    - json/
