const Map<String, dynamic> langJA = {
  'securityOfAccount': 'アカウントのセキュリティ',
  'securityDesc': '高度な暗号化と多層認証により、ワークショップと車両のデータを保護します。',
  'password': 'パスワード',
  'currentPassword': '現在のパスワード',
  'newPassword': '新しいパスワード',
  'confirmation': '確認',
  'confirmPasswordHint': '確認用パスワード',
  'updatePassword': 'パスワードを更新',
  'accountSecuritySettings': 'アカウントセキュリティ設定',
  'personalInformation': '個人情報',
  'personalInfoDesc':
      '正確でパーソナライズされたAuto Finder service体験を提供するために、アカウントの詳細を更新してください。',
  'fullName': '氏名',
  'fullNameHint': 'あなたの氏名',
  'email': 'メールアドレス',
  'phoneNumber': '電話番号',
  'saveChanges': '変更を保存',
  'cancel': 'キャンセル',
  'profileSettings': 'プロフィール設定',
  'title': 'Auto Finder',
  'theme': 'ダーク/ライトモード',
  'themeSubtitle': '精密なテーマを切り替えます',
  'language': '言語',
  'languageSubtitle': 'ご希望の言語を選択してください',
  'profile': 'プロフィール',
  'accountAndSecurity': 'アカウントとセキュリティ',
  'accountSecurity': 'アカウントセキュリティ',
  'accountSecuritySubtitle': 'パスワードの更新',
  'editProfile': 'プロフィール編集',
  'editProfileSubtitle': '個人詳細と資格情報の更新',
  'preferences': '環境設定',
  'logout': 'ログアウト',
  'logoutSubtitle': 'アトリエアカウントからサインアウトします',
  'home': 'ホーム',
  'search': '検索',
  'post': '投稿',
  'favorite': 'お気に入り',
  'addWorkshopTitle': 'ワークショップを追加',
  'identityTitle': 'ワークショップの身元',
  'identitySubtitle': 'ブランドとコアとなる運用の詳細を定義します。',
  'phoneLabel': '電話番号',
  'workshopNameLabel': 'ワークショップ名',
  'workshopNameHint': '例：Precision Gearhead Labs',
  'missionLabel': 'ミッションステートメント',
  'missionHint': '技術的な専門知識や\nワークショップの価値観を\n入力してください...',
  'specializationLabel': '専門分野',

  'locationTitle': '配置場所',
  'locationSubtitle': 'テクニカルネットワークマップ上にワークショップを固定します。',
  'locationChange': '変更',
  'locationAddressHint': '住所',

  'servicesTitle': 'サービス能力',
  'servicesSubtitle': 'アトリエが提供する専門サービスを選択してください。',
  'addService': 'サービスを追加',

  'scheduleTitle': '週間スケジュールの設定',
  'scheduleOpen': '営業',
  'scheduleClosed': '休業',
  'openingTime': '開店時間',
  'closingTime': '閉店時間',
  'scheduleError': '開店時間は閉店時間より前でなければなりません！',
  'noPhotoUploaded': 'アップロードされた写真はありません。',

  'documentationTitle': 'ドキュメンテーション',
  'documentationSubtitle': '施設の高解像度画像をアップロードしてください。',
  'photoCount': '枚の写真',
  'addPhoto': '写真を追加',
  'maxPhotoWarning': '最大4枚までです。新しい写真を追加するには、既存の写真を削除してください。',
};
