const Map<String, dynamic> langEN = {
  'securityOfAccount': 'Security of Your Account',
  'securityDesc':
      'Protect your workshop and vehicle data with advanced encryption and multi-layered authentication.',
  'password': 'Password',
  'currentPassword': 'Current Password',
  'newPassword': 'New Password',
  'confirmation': 'Confirmation',
  'confirmPasswordHint': 'Confirmation Password',
  'updatePassword': 'Update Password',
  'accountSecuritySettings': 'Account Security Settings',
  'personalInformation': 'Personal Information',
  'personalInfoDesc':
      'Update your account details to ensure a precise and personalized Auto Finder service experience.',
  'fullName': 'Full Name',
  'fullNameHint': 'Your full name',
  'email': 'Email',
  'phoneNumber': 'Phone Number',
  'saveChanges': 'Save Changes',
  'cancel': 'Cancel',
  'profileSettings': 'Profile Settings',
  'title': 'Auto Finder',
  'theme': 'Dark/Light Mode',
  'themeSubtitle': 'Switch between precision themes',
  'language': 'Language',
  'languageSubtitle': 'Choose your preferred language',
  'profile': 'Profile',
  'accountAndSecurity': 'ACCOUNT & SECURITY',
  'accountSecurity': 'Account Security',
  'accountSecuritySubtitle': 'Update your password',
  'editProfile': 'Edit Profile',
  'editProfileSubtitle': 'Update your personal details and credentials',
  'preferences': 'PREFERENCES',
  'logout': 'Logout',
  'logoutSubtitle': 'Sign out of your atelier account',
  'home': 'Home',
  'search': 'Search',
  'post': 'Post',
  'favorite': 'Favorite',
  'addWorkshopTitle': 'Add Workshop',
  'identityTitle': 'Workshop Identity',
  'identitySubtitle': 'Define your brand and core operational details.',
  'phoneLabel': 'PHONE NUMBER',
  'workshopNameLabel': 'WORKSHOP NAME',
  'workshopNameHint': 'e.g. Precision Gearhead Labs',
  'missionLabel': 'MISSION STATEMENT',
  'missionHint': 'Describe your technical\nexpertise and workshop\nvalues...',
  'specializationLabel': 'SPECIALIZATION',
  
  'locationTitle': 'Deployment Location',
  'locationSubtitle': 'Pin your workshop on our technical network map.',
  'locationChange': 'Change',
  'locationAddressHint': 'Address',
  
  'servicesTitle': 'Service Capabilities',
  'servicesSubtitle': 'Select the specialized services your atelier provides.',
  'addService': 'Add Service',
  
  'scheduleTitle': 'WEEKLY SCHEDULE CONFIGURATION',
  'scheduleOpen': 'OPEN',
  'scheduleClosed': 'CLOSED',
  'openingTime': 'OPENING TIME',
  'closingTime': 'CLOSING TIME',
  'scheduleError': 'Jam buka harus lebih awal dari jam tutup!',
  'noPhotoUploaded': 'Belum ada foto yang diunggah.',
  
  'documentationTitle': 'Documentation',
  'documentationSubtitle': 'Upload high-resolution images of your facility.',
  'photoCount': 'foto',
  'addPhoto': 'ADD PHOTO',
  'maxPhotoWarning': 'Maksimal 4 foto. Hapus foto yang ada untuk menambah yang baru.',
};
