const Map<String, dynamic> langJA = {
  'securityOfAccount': 'アカウントのセキュリティ',
  'securityDesc': '高度な暗号化と多層認証により、ワークショップと車両のデータを保護します。',
  'password': 'パスワード',
  'currentPassword': '現在のパスワード',
  'newPassword': '新しいパスワード',
  'confirmation': '確認',
  'confirmPasswordHint': '確認用パスワード',
  'updatePassword': 'パスワードを更新',
  'accountSecuritySettings': 'アカウントセキュリティ設定',
  'personalInformation': '個人情報',
  'personalInfoDesc':
      '正確でパーソナライズされたAuto Finder service体験を提供するために、アカウントの詳細を更新してください。',
  'fullName': '氏名',
  'fullNameHint': 'あなたの氏名',
  'email': 'メールアドレス',
  'phoneNumber': '電話番号',
  'saveChanges': '変更を保存',
  'cancel': 'キャンセル',
  'profileSettings': 'プロフィール設定',
  'title': 'Auto Finder',
  'theme': 'ダーク/ライトモード',
  'themeSubtitle': '精密なテーマを切り替えます',
  'language': '言語',
  'languageSubtitle': 'ご希望の言語を選択してください',
  'profile': 'プロフィール',
  'accountAndSecurity': 'アカウントとセキュリティ',
  'accountSecurity': 'アカウントセキュリティ',
  'accountSecuritySubtitle': 'パスワードの更新',
  'editProfile': 'プロフィール編集',
  'editProfileSubtitle': '個人詳細と資格情報の更新',
  'preferences': '環境設定',
  'logout': 'ログアウト',
  'logoutSubtitle': 'アトリエアカウントからサインアウトします',
  'home': 'ホーム',
  'search': '検索',
  'post': '投稿',
  'favorite': 'お気に入り',
  'addWorkshopTitle': 'ワークショップを追加',
  'identityTitle': 'ワークショップの身元',
  'identitySubtitle': 'ブランドとコアとなる運用の詳細を定義します。',
  'phoneLabel': '電話番号',
  'workshopNameLabel': 'ワークショップ名',
  'workshopNameHint': '例：Precision Gearhead Labs',
  'missionLabel': 'ミッションステートメント',
  'missionHint': '技術的な専門知識や\nワークショップの価値観を\n入力してください...',
  'specializationLabel': '専門分野',

  'locationTitle': '配置場所',
  'locationSubtitle': 'テクニカルネットワークマップ上にワークショップを固定します。',
  'locationChange': '変更',
  'locationAddressHint': '住所',

  'servicesTitle': 'サービス能力',
  'servicesSubtitle': 'アトリエが提供する専門サービスを選択してください。',
  'addService': 'サービスを追加',

  // Service Picker Sheet
  'chooseService': 'サービスを選択',
  'searchService': 'サービスを検索...',
  'selected': '選択済み',
  'confirmSelection': '選択を確認',
  'save': '保存 ',
  'servicesLabel': ' サービス',
  'serviceNotFound': ' が見つかりません',

  'scheduleTitle': '週間スケジュールの設定',
  'scheduleOpen': '営業',
  'scheduleClosed': '休業',
  'openingTime': '開店時間',
  'closingTime': '閉店時間',
  'scheduleError': '開店時間は閉店時間より前でなければなりません！',
  'noPhotoUploaded': 'アップロードされた写真はありません。',

  'documentationTitle': 'ドキュメンテーション',
  'documentationSubtitle': '施設の高解像度画像をアップロードしてください。',
  'photoCount': '枚の写真',
  'addPhoto': '写真を追加',
  'maxPhotoWarning': '最大4枚までです。新しい写真を追加するには、既存の写真を削除してください。',
  'minPhotoWarning': 'ワークショップの証明書類として、少なくとも 1 枚の写真をアップロードしてください。',

  // Auth
  'back': '戻る',
  'signIn': 'ログイン',
  'signUp': '新規登録',
  'noAccount': 'アカウントをお持ちでないですか？',
  'alreadyHaveAccount': 'すでにアカウントをお持ちですか？',
  'loginWelcomeBack': 'Auto Finderにおかえりなさい',
  'loginSubtitle': 'ログインして、最高のワークショップを簡単かつ迅速に見つけましょう。',
  'welcomeTitle': 'Auto Finderへようこそ',
  'welcomeSubtitle': 'プレシジョンエンジニアリングとケアのための最高のワークショップ検索アプリ。',
  'registerSubtitle': '今すぐ登録して、最高のワークショップを簡単かつ迅速に見つけましょう。',
  'continueWithGoogle': 'Googleで続ける',
  'orText': 'または',
  'signInWithEmail': 'メールでログイン',
  'username': 'ユーザー名',
  'googleSignInFailed': 'Googleへの接続に失敗しました',

  // Home
  'findWorkshop': 'ワークショップを探す',
  'detectingLocation': '位置情報を検出中...',
  'locationLabel': '場所: ',

  // Location Picker
  'pickLocation': '場所を選択',
  'confirm': '確認',
  'searchLocation': '通り、地域、または都市を検索...',
  'selectedLocation': '選択した場所',
  'confirmLocation': '場所を確認',
  'tapMapToSelect': '地図をタップして場所を選択します',

  // Add Workshop
  'createNewPost': '新しい投稿を作成',
  'createNewPostSubtitle': 'サービス体験やワークショップの推薦を新しい投稿でシェアしましょう。',
  'workshopAddedSuccess': 'ワークショップが正常に追加されました！',
  'postWorkshop': 'ワークショップを投稿',
  'next': '次へ',
  'stepIdentity': 'ID情報',
  'stepServices': 'サービス',
  'stepLocation': '場所',
  'stepUptime': 'スケジュール',
  'stepVerify': '確認',

  // Validation
  'completeAllFields': '必須項目をすべて正しく入力してください',
  'minServiceWarning': '少なくとも1つのサービスを選択してください',
  'fixScheduleWarning': '無効な営業時間を修正してください',
  'invalidUptimeWarning': '無効な稼働時間データを修正してください',
  'failedToSubmit': 'データの送信に失敗しました',

  // Profile image source
  'changeProfilePhoto': 'プロフィール写真を変更',
  'takePhotoCamera': 'カメラで撮影',
  'chooseFromGallery': 'ギャラリーから選択',
  'currentPasswordEmpty': '現在のパスワードを入力してください',
  'newPasswordEmpty': '新しいパスワードを入力してください',
  'passwordMinLength': 'パスワードは6文字以上で入力してください',
  'confirmPasswordEmpty': '確認用パスワードを入力してください',
  'passwordMismatch': 'パスワードが一致しません',

  'usernameEmpty': 'ユーザー名は必須です',
  'usernameMinLength': 'ユーザー名は3文字以上で入力してください',
  'phoneNumberEmpty': '電話番号は必須です',
  'phoneNumberInvalid': '無効な電話番号です',

  'emailEmpty': 'メールアドレスを入力してください',
  'emailInvalid': '無効なメールアドレス形式です',
  'emailMaxLength': '最大50文字までです',
  'passwordEmpty': 'パスワードを入力してください',
  'phoneEmpty': '電話番号を入力してください',
  'phoneInvalid': '電話番号の形式が正しくありません',
  'passwordConfirmEmpty': 'パスワードの確認を入力してください',
  'loadingMessage': '少々お待ちください...',
  'featuredWorkshops': '最も人気',
  'workshopNearby': '近くのワークショップ',
  'findSpecialist': '専門のワークショップを探す...',
  'viewAll': 'すべて表示',
  'workshopDetails': 'ワークショップの詳細',
};
