const Map<String, dynamic> langTH = {
  'securityOfAccount': 'ความปลอดภัยของบัญชีคุณ',
  'securityDesc':
      'ปกป้องข้อมูลอู่และยานพาหนะของคุณด้วยการเข้ารหัสขั้นสูงและการยืนยันตัวตนหลายชั้น',
  'password': 'รหัสผ่าน',
  'currentPassword': 'รหัสผ่านปัจจุบัน',
  'newPassword': 'รหัสผ่านใหม่',
  'confirmation': 'ยืนยัน',
  'confirmPasswordHint': 'ยืนยันรหัสผ่าน',
  'updatePassword': 'อัปเดตรหัสผ่าน',
  'accountSecuritySettings': 'ตั้งค่าความปลอดภัยบัญชี',
  'personalInformation': 'ข้อมูลส่วนตัว',
  'personalInfoDesc':
      'อัปเดตรายละเอียดบัญชีของคุณเพื่อให้มั่นใจว่าจะได้รับประสบการณ์บริการ Auto Finder ที่แม่นยำและเป็นส่วนตัว',
  'fullName': 'ชื่อ-นามสกุล',
  'fullNameHint': 'ชื่อเต็มของคุณ',
  'email': 'อีเมล',
  'phoneNumber': 'เบอร์โทรศัพท์',
  'saveChanges': 'บันทึกการเปลี่ยนแปลง',
  'cancel': 'ยกเลิก',
  'profileSettings': 'ตั้งค่าโปรไฟล์',
  'title': 'Auto Finder',
  'theme': 'โหมดมืด/สว่าง',
  'themeSubtitle': 'สลับระหว่างธีมที่มีความแม่นยำ',
  'language': 'ภาษา',
  'languageSubtitle': 'เลือกภาษาที่คุณต้องการ',
  'profile': 'โปรไฟล์',
  'accountAndSecurity': 'บัญชีและความปลอดภัย',
  'accountSecurity': 'ความปลอดภัยของบัญชี',
  'accountSecuritySubtitle': 'อัปเดตรหัสผ่านของคุณ',
  'editProfile': 'แก้ไขโปรไฟล์',
  'editProfileSubtitle': 'อัปเดตรายละเอียดส่วนบุคคลและข้อมูลประจำตัว',
  'preferences': 'การตั้งค่า',
  'logout': 'ออกจากระบบ',
  'logoutSubtitle': 'ออกจากระบบบัญชี atelier ของคุณ',
  'home': 'หน้าแรก',
  'search': 'ค้นหา',
  'post': 'โพสต์',
  'favorite': 'รายการโปรด',
  'addWorkshopTitle': 'เพิ่มอู่ซ่อมรถ',
  'identityTitle': 'ข้อมูลอู่ซ่อมรถ',
  'identitySubtitle': 'กำหนดแบรนด์และรายละเอียดการดำเนินงานหลักของคุณ',
  'phoneLabel': 'เบอร์โทรศัพท์',
  'workshopNameLabel': 'ชื่ออู่ซ่อมรถ',
  'workshopNameHint': 'เช่น Precision Gearhead Labs',
  'missionLabel': 'พันธกิจ',
  'missionHint':
      'อธิบายความเชี่ยวชาญ\nทางเทคนิคและคุณค่า\nของอู่ซ่อมรถของคุณ...',
  'specializationLabel': 'ความเชี่ยวชาญพิเศษ',

  'locationTitle': 'ตำแหน่งที่ตั้ง',
  'locationSubtitle': 'ปักหมุดอู่ซ่อมรถของคุณบนแผนที่เครือข่ายเทคนิคของเรา',
  'locationChange': 'เปลี่ยน',
  'locationAddressHint': 'ที่อยู่',

  'servicesTitle': 'ความสามารถในการบริการ',
  'servicesSubtitle': 'เลือกบริการเฉพาะทางที่ atelier ของคุณให้บริการ',
  'addService': 'เพิ่มบริการ',

  'scheduleTitle': 'การตั้งค่าตารางเวลาประจำสัปดาห์',
  'scheduleOpen': 'เปิด',
  'scheduleClosed': 'ปิด',
  'openingTime': 'เวลาเปิด',
  'closingTime': 'เวลาปิด',
  'scheduleError': 'เวลาเปิดต้องอยู่ก่อนเวลาปิด!',
  'noPhotoUploaded': 'ยังไม่มีการอัปโหลดรูปภาพ',

  'documentationTitle': 'เอกสารภาพถ่าย',
  'documentationSubtitle': 'อัปโหลดรูปภาพความละเอียดสูงของสถานประกอบการของคุณ',
  'photoCount': 'รูปภาพ',
  'addPhoto': 'เพิ่มรูปภาพ',
  'maxPhotoWarning':
      'อัปโหลดได้สูงสุด 4 รูป กรุณาลบรูปภาพที่มีอยู่เพื่อเพิ่มรูปภาพใหม่',
};
