const Map<String, dynamic> langTH = {
  'titleEditWorkshop': 'แก้ไขเวิร์กชอป',
  'descEditWorkshop':
      'อัปเดตรายละเอียดเวิร์กชอปของคุณเพื่อให้มั่นใจว่าจะได้รับประสบการณ์ Auto Finder ที่แม่นยำและเป็นส่วนตัว',
  'myPostDescription':
      'การควบคุมที่แม่นยำเหนือรายการบริการของคุณ รักษารายละเอียดเวิร์กชอปของคุณให้ถูกต้องเพื่อให้มั่นใจในความไว้วางใจของลูกค้าที่สูงและอัตราการจองที่ดี',
  'titleMyPost': 'จัดการโพสต์ของฉัน',
  'deleteTitleConfirmation': 'ลบเวิร์กชอปหรือไม่?',
  'deleteConfirmation': 'คุณแน่ใจหรือไม่ว่าต้องการลบโพสต์สัมมนานี้?',
  'securityOfAccount': 'ความปลอดภัยของบัญชีคุณ',
  'securityDesc':
      'ปกป้องข้อมูลอู่และยานพาหนะของคุณด้วยการเข้ารหัสขั้นสูงและการยืนยันตัวตนหลายชั้น',
  'password': 'รหัสผ่าน',
  'currentPassword': 'รหัสผ่านปัจจุบัน',
  'newPassword': 'รหัสผ่านใหม่',
  'confirmation': 'ยืนยัน',
  'confirmPasswordHint': 'ยืนยันรหัสผ่าน',
  'updatePassword': 'อัปเดตรหัสผ่าน',
  'accountSecuritySettings': 'ตั้งค่าความปลอดภัยบัญชี',
  'personalInformation': 'ข้อมูลส่วนตัว',
  'personalInfoDesc':
      'อัปเดตรายละเอียดบัญชีของคุณเพื่อให้มั่นใจว่าจะได้รับประสบการณ์บริการ Auto Finder ที่แม่นยำและเป็นส่วนตัว',
  'fullName': 'ชื่อ-นามสกุล',
  'fullNameHint': 'ชื่อเต็มของคุณ',
  'email': 'อีเมล',
  'phoneNumber': 'เบอร์โทรศัพท์',
  'saveChanges': 'บันทึกการเปลี่ยนแปลง',
  'cancel': 'ยกเลิก',
  'profileSettings': 'ตั้งค่าโปรไฟล์',
  'title': 'Auto Finder',
  'theme': 'โหมดมืด/สว่าง',
  'themeSubtitle': 'สลับระหว่างธีมที่มีความแม่นยำ',
  'language': 'ภาษา',
  'languageSubtitle': 'เลือกภาษาที่คุณต้องการ',
  'profile': 'โปรไฟล์',
  'accountAndSecurity': 'บัญชีและความปลอดภัย',
  'accountSecurity': 'ความปลอดภัยของบัญชี',
  'accountSecuritySubtitle': 'อัปเดตรหัสผ่านของคุณ',
  'editProfile': 'แก้ไขโปรไฟล์',
  'editProfileSubtitle': 'อัปเดตรายละเอียดส่วนบุคคลและข้อมูลประจำตัว',
  'preferences': 'การตั้งค่า',
  'logout': 'ออกจากระบบ',
  'logoutSubtitle': 'ออกจากระบบบัญชี atelier ของคุณ',
  'home': 'หน้าแรก',
  'search': 'ค้นหา',
  'post': 'โพสต์',
  'favorite': 'รายการโปรด',
  'addWorkshopTitle': 'เพิ่มอู่ซ่อมรถ',
  'identityTitle': 'ข้อมูลอู่ซ่อมรถ',
  'identitySubtitle': 'กำหนดแบรนด์และรายละเอียดการดำเนินงานหลักของคุณ',
  'phoneLabel': 'เบอร์โทรศัพท์',
  'workshopNameLabel': 'ชื่ออู่ซ่อมรถ',
  'workshopNameHint': 'เช่น Precision Gearhead Labs',
  'missionLabel': 'พันธกิจ',
  'missionHint':
      'อธิบายความเชี่ยวชาญ\nทางเทคนิคและคุณค่า\nของอู่ซ่อมรถของคุณ...',
  'specializationLabel': 'ความเชี่ยวชาญพิเศษ',

  'locationTitle': 'ตำแหน่งที่ตั้ง',
  'locationSubtitle': 'ปักหมุดอู่ซ่อมรถของคุณบนแผนที่เครือข่ายเทคนิคของเรา',
  'locationChange': 'เปลี่ยน',
  'locationAddressHint': 'ที่อยู่',

  'servicesTitle': 'ความสามารถในการบริการ',
  'servicesSubtitle': 'เลือกบริการเฉพาะทางที่ atelier ของคุณให้บริการ',
  'addService': 'เพิ่มบริการ',

  // Service Picker Sheet
  'chooseService': 'เลือกบริการ',
  'searchService': 'ค้นหาบริการ...',
  'selected': 'เลือกแล้ว',
  'confirmSelection': 'ยืนยันการเลือก',
  'save': 'บันทึก ',
  'servicesLabel': ' บริการ',
  'serviceNotFound': ' ไม่พบ',

  'scheduleTitle': 'การตั้งค่าตารางเวลาประจำสัปดาห์',
  'scheduleOpen': 'เปิด',
  'scheduleClosed': 'ปิด',
  'openingTime': 'เวลาเปิด',
  'closingTime': 'เวลาปิด',
  'scheduleError': 'เวลาเปิดต้องอยู่ก่อนเวลาปิด!',
  'noPhotoUploaded': 'ยังไม่มีการอัปโหลดรูปภาพ',

  'documentationTitle': 'เอกสารภาพถ่าย',
  'documentationSubtitle': 'อัปโหลดรูปภาพความละเอียดสูงของสถานประกอบการของคุณ',
  'photoCount': 'รูปภาพ',
  'addPhoto': 'เพิ่มรูปภาพ',
  'maxPhotoWarning':
      'อัปโหลดได้สูงสุด 4 รูป กรุณาลบรูปภาพที่มีอยู่เพื่อเพิ่มรูปภาพใหม่',
  'minPhotoWarning':
      'กรุณาอัปโหลดรูปภาพอย่างน้อย 1 รูปเพื่อเป็นเอกสารประกอบอู่ซ่อมรถ',

  // Auth
  'back': 'กลับ',
  'signIn': 'เข้าสู่ระบบ',
  'signUp': 'สมัครสมาชิก',
  'noAccount': 'ยังไม่มีบัญชี?',
  'alreadyHaveAccount': 'มีบัญชีอยู่แล้ว?',
  'loginWelcomeBack': 'ยินดีต้อนรับกลับสู่ Auto Finder',
  'loginSubtitle':
      'เข้าสู่ระบบเพื่อค้นหาอู่ซ่อมรถที่ดีที่สุดได้อย่างง่ายดายและรวดเร็ว',
  'welcomeTitle': 'ยินดีต้อนรับสู่ Auto Finder',
  'welcomeSubtitle':
      'แอปค้นหาอู่ซ่อมรถที่ดีที่สุดสำหรับวิศวกรรมที่แม่นยำและการดูแลรักษา',
  'registerSubtitle':
      'สมัครสมาชิกเพื่อค้นหาอู่ซ่อมรถที่ดีที่สุดได้อย่างง่ายดายและรวดเร็ว',
  'continueWithGoogle': 'ดำเนินการต่อด้วย Google',
  'orText': 'หรือ',
  'signInWithEmail': 'เข้าสู่ระบบด้วยอีเมล',
  'username': 'ชื่อผู้ใช้',
  'googleSignInFailed': 'ไม่สามารถเชื่อมต่อกับ Google ได้',

  // Home
  'findWorkshop': 'ค้นหาอู่ซ่อมรถ',
  'detectingLocation': 'กำลังตรวจจับตำแหน่ง...',
  'locationLabel': 'ตำแหน่ง: ',

  // Location Picker
  'pickLocation': 'เลือกสถานที่',
  'confirm': 'ยืนยัน',
  'searchLocation': 'ค้นหาถนน พื้นที่ หรือเมือง...',
  'selectedLocation': 'สถานที่ที่เลือก',
  'confirmLocation': 'ยืนยันสถานที่',
  'tapMapToSelect': 'แตะบนแผนที่เพื่อเลือกสถานที่',

  // Add Workshop
  'createNewPost': 'สร้างโพสต์ใหม่',
  'createNewPostSubtitle':
      'แชร์ประสบการณ์บริการหรือคำแนะนำอู่ซ่อมรถผ่านโพสต์ใหม่',
  'workshopAddedSuccess': 'เพิ่มอู่ซ่อมรถสำเร็จแล้ว!',
  'postWorkshop': 'โพสต์อู่ซ่อมรถ',
  'next': 'ถัดไป',
  'stepIdentity': 'ข้อมูลตัวตน',
  'stepServices': 'บริการ',
  'stepLocation': 'ตำแหน่ง',
  'stepUptime': 'ตารางเวลา',
  'stepVerify': 'ยืนยัน',

  // Validation
  'completeAllFields': 'กรุณากรอกข้อมูลในช่องที่จำเป็นให้ครบถ้วนและถูกต้อง',
  'minServiceWarning': 'กรุณาเลือกบริการอย่างน้อย 1 รายการ',
  'fixScheduleWarning': 'กรุณาแก้ไขเวลาทำการที่ไม่ถูกต้อง',
  'invalidUptimeWarning': 'กรุณาแก้ไขข้อมูลเวลาทำการที่ไม่ถูกต้อง',
  'failedToSubmit': 'ส่งข้อมูลล้มเหลว',

  // Profile image source
  'changeProfilePhoto': 'เปลี่ยนรูปโปรไฟล์',
  'takePhotoCamera': 'ถ่ายรูปด้วยกล้อง',
  'chooseFromGallery': 'เลือกจากแกลเลอรี่',

  'currentPasswordEmpty': 'กรุณากรอกรหัสผ่านปัจจุบัน',
  'newPasswordEmpty': 'กรุณากรอกรหัสผ่านใหม่',
  'passwordMinLength': 'รหัสผ่านต้องมีความยาวอย่างน้อย 6 ตัวอักษร',
  'confirmPasswordEmpty': 'กรุณากรอกเพื่อยืนยันรหัสผ่าน',
  'passwordMismatch': 'รหัสผ่านไม่ตรงกัน',
  'usernameEmpty': 'กรุณากรอกชื่อผู้ใช้',
  'usernameMinLength': 'ชื่อผู้ใช้ต้องมีความยาวอย่างน้อย 3 ตัวอักษร',
  'phoneNumberEmpty': 'กรุณากรอกเบอร์โทรศัพท์',
  'phoneNumberInvalid': 'เบอร์โทรศัพท์ไม่ถูกต้อง',

  'emailEmpty': 'กรุณากรอกอีเมล',
  'emailInvalid': 'รูปแบบอีเมลไม่ถูกต้อง',
  'emailMaxLength': 'สูงสุดไม่เกิน 50 ตัวอักษร',
  'passwordEmpty': 'กรุณากรอกรหัสผ่าน',
  'phoneEmpty': 'กรุณากรอกเบอร์โทรศัพท์',
  'phoneInvalid': 'รูปแบบเบอร์โทรศัพท์ไม่ถูกต้อง',
  'passwordConfirmEmpty': 'กรุณากรอกเพื่อยืนยันรหัสผ่านของคุณ',
  'loadingMessage': 'โปรดรอสักครู่...',
  'featuredWorkshops': 'ยอดนิยมที่สุด',
  'workshopNearby': 'อู่ซ่อมรถใกล้เคียง',
  'findSpecialist': 'ค้นหาอู่ซ่อมรถเฉพาะทาง...',
  'viewAll': 'ดูทั้งหมด',
  'detailWorkshop': 'รายละเอียดเวิร์กชอป',
  'aboutTheWorkshop': 'เกี่ยวกับเวิร์กชอป',
  'oprationalHours': 'เวลาทำการ',
  'availableServices': 'บริการที่สามารถทำได้',
  'location': 'ที่อยู่',
  'getDirections': 'ขอเส้นทาง',
  'call': 'โทร',
  'clientReviews': 'รีวิวจากลูกค้า',
  'alreadyReviewed': 'รีวิวแล้ว ✓',
  'writeReview': 'เขียนรีวิว',
  'noReviewsYet': 'ยังไม่มีรีวิว เป็นคนแรกเลย!',
  'customerLabel': 'ลูกค้า',
  'editLabel': 'แก้ไข',
  'deleteLabel': 'ลบ',
  'replyLabel': 'ตอบกลับ',
  'cancelLabel': 'ยกเลิก',
  'deleteReviewTitle': 'ลบรีวิว?',
  'deleteReviewContent': 'รีวิวที่ถูกลบไม่สามารถกู้คืนได้',
  'rateExperienceInstruction': 'ให้คะแนนประสบการณ์ของคุณกับอู่ซ่อมรถนี้',
  'updateExperienceInstruction': 'อัปเดตคะแนนและประสบการณ์ของคุณ',
  'reviewFieldHint': 'บอกเราเกี่ยวกับประสบการณ์ของคุณที่อู่ซ่อมรถนี้...',
  'submitReview': 'ส่งรีวิว',
  'editReviewTitle': 'แก้ไขรีวิว',
  'replyReviewTitle': 'ตอบกลับรีวิว',
  'replyFieldHint': 'พิมพ์คำตอบของคุณที่นี่...',
  'sendReply': 'ส่งคำตอบ',
};
