const Map<String, dynamic> langZH = {
  'securityOfAccount': '账户安全',
  'securityDesc': '通过高级加密和多层身份验证保护您的车间和车辆数据。',
  'password': '密码',
  'currentPassword': '当前密码',
  'newPassword': '新密码',
  'confirmation': '确认',
  'confirmPasswordHint': '确认密码',
  'updatePassword': '更新密码',
  'accountSecuritySettings': '账户安全设置',
  'personalInformation': '个人信息',
  'personalInfoDesc': '更新您的账户详细信息，以确保获得精确且个性化的 Auto Finder 服务体验。',
  'fullName': '姓名',
  'fullNameHint': '您的全名',
  'email': '电子邮箱',
  'phoneNumber': '手机号码',
  'saveChanges': '保存更改',
  'cancel': '取消',
  'profileSettings': '个人资料设置',
  'title': 'Auto Finder',
  'theme': '深色/浅色模式',
  'themeSubtitle': '在精准主题之间切换',
  'language': '语言',
  'languageSubtitle': '选择您的首选语言',
  'profile': '个人资料',
  'accountAndSecurity': '账户与安全',
  'accountSecurity': '账户安全',
  'accountSecuritySubtitle': '更新您的密码',
  'editProfile': '编辑个人资料',
  'editProfileSubtitle': '更新您的个人详细信息和凭据',
  'preferences': '偏好设置',
  'logout': '退出登录',
  'logoutSubtitle': '退出您的工作室账户',
  'home': '首页',
  'search': '搜索',
  'post': '发布',
  'favorite': '收藏',
  'addWorkshopTitle': '添加车间',
  'identityTitle': '车间身份信息',
  'identitySubtitle': '定义您的品牌和核心运营详细信息。',
  'phoneLabel': '手机号码',
  'workshopNameLabel': '车间名称',
  'workshopNameHint': '例如：Precision Gearhead Labs',
  'missionLabel': '使命宣言',
  'missionHint': '描述您的技术专长\n和车间价值观...',
  'specializationLabel': '专业领域',
  
  'locationTitle': '部署位置',
  'locationSubtitle': '在我们的技术网络地图上标记您的车间。',
  'locationChange': '更改',
  'locationAddressHint': '详细地址',
  
  'servicesTitle': '服务能力',
  'servicesSubtitle': '选择您的工作室提供的专业服务。',
  'addService': '添加服务',
  
  'scheduleTitle': '每周时间表配置',
  'scheduleOpen': '营业',
  'scheduleClosed': '歇业',
  'openingTime': '开门时间',
  'closingTime': '关门时间',
  'scheduleError': '开门时间必须早于关门时间！',
  'noPhotoUploaded': '未上传任何照片。',
  
  'documentationTitle': '文件与图片',
  'documentationSubtitle': '上传您车间设施的高清图片。',
  'photoCount': '张照片',
  'addPhoto': '添加照片',
  'maxPhotoWarning': '最多只能上传 4 张照片。请删除现有照片以添加新照片。',
};
