// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiutOkjn5PcM3WfM_lldoHk5PIhi59ruY',
    appId: '1:241898456284:web:d82b5ce2e64b0739b3e019',
    messagingSenderId: '241898456284',
    projectId: 'autofinder-7d747',
    authDomain: 'autofinder-7d747.firebaseapp.com',
    storageBucket: 'autofinder-7d747.firebasestorage.app',
    measurementId: 'G-C06DMQDV5R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWrRAOuKX9M3F-f5Ni1oYe9uQtqNSr44I',
    appId: '1:241898456284:android:5b1290d5c2aa5c56b3e019',
    messagingSenderId: '241898456284',
    projectId: 'autofinder-7d747',
    storageBucket: 'autofinder-7d747.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC35PBSWiFTLf6mxlEQu0PbcPBqR8Gf8v8',
    appId: '1:241898456284:ios:44272c323194e6c5b3e019',
    messagingSenderId: '241898456284',
    projectId: 'autofinder-7d747',
    storageBucket: 'autofinder-7d747.firebasestorage.app',
    iosBundleId: 'com.example.autofinder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC35PBSWiFTLf6mxlEQu0PbcPBqR8Gf8v8',
    appId: '1:241898456284:ios:44272c323194e6c5b3e019',
    messagingSenderId: '241898456284',
    projectId: 'autofinder-7d747',
    storageBucket: 'autofinder-7d747.firebasestorage.app',
    iosBundleId: 'com.example.autofinder',
  );
}
